### ISSUE TITLE
[Show Groups] Groups command accepts an unknown parameter

### ISSUE THREAD

**Issue by hyxnnii** [AY2425S1-CS2103T-W08-4/tp#113]
<img width="738" alt="Screenshot 2024-10-30 at 4 53 05 PM" src="https://github.com/user-attachments/assets/a101f6b6-0ed7-41ad-8030-66c75a9a7aac">

Groups command should give an error message since it should not accept any kind of paremeter.

**Comment by wenjebs** [comment]
list command allows this too so i think its should be fine :-)
