### ISSUE TITLE
[Group] Wrong group member name does not give error

### ISSUE THREAD

**Issue by hyxnnii** [AY2425S1-CS2103T-W08-4/tp#115]
<img width="736" alt="Screenshot 2024-10-30 at 5 01 55 PM" src="https://github.com/user-attachments/assets/64c04b4b-d730-4042-9c04-037f57c39ece">

When multiple members are to be added to the group and one of the names are wrongly typed, it should still lead to an error of no matching name. Currently group is successfully created with only those correctly typed names included in the new group.

**Comment by wenjebs** [comment]
sounds similar to #113
