### ISSUE TITLE
[List] list accepts additional arguments

### ISSUE THREAD

**Issue by yimjianbing** [AY2425S1-CS2103T-W08-4/tp#122]
![image](https://github.com/user-attachments/assets/4bef94c2-81a7-4a37-81f2-d7112bad9cc5)
While using the list command, typing in "List abc", although gives the same output, could be abit misleading, maybe bettet to say that its an invalid command format instead

**Comment by wenjebs** [comment]
similarly to #113, i think this is unnecessary? perhaps the command should be able to function normally as expected with any additional arguments?
