### ISSUE TITLE
[PE-D][Tester B] Classes with special characters could not be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-4/tp#196]
![image.png](https://raw.githubusercontent.com/Nicholascyx/ped/main/files/61268c33-8e74-45fc-8330-0d0557f5e3dc.png)

Steps to reproduce:
- Add person with classes with special characters (4-A)

Expected:
- The person should be added.

Actual:
- The person is not added and error message is shown.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Nicholascyx/ped#6

**Comment by hyxnnii** [comment]
Solution: UG can include example of inputs that will lead to invalid class error
