### ISSUE TITLE
[PE-D][Tester E] export function only exports students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-4/tp#202]
If you are only able to export students and imagine you have 100 groups of students, you would not be able to know from the csv file which students are in which group, making it such that you have to either refer to the app or the json file, making it really inconvenient and sort of defeats the purpose of the export function

Would be better to be able to export groups too

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ylchin/ped#6

**Comment by Hoodini231** [comment]
Feature freeze and added in ug as future plans
