### ISSUE TITLE
[PE-D][Tester D] findGroup does not work when order of words is changed

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-4/tp#230]
In this scenario, I have a group named abcdef

![image.png](https://raw.githubusercontent.com/niclammm/ped/main/files/d5b175f5-304a-4dec-9274-f098caca6502.png)

group find works when I use findGroup works for abcdefg but does not work for gfedcba where the order is the same 

![image.png](https://raw.githubusercontent.com/niclammm/ped/main/files/cbbcd054-e785-496f-b9b2-7ae00b01ff65.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: niclammm/ped#13

**Comment by Hoodini231** [comment]
Misunderstanding on different order of keywords. abcdefg is a different keyword than gfedcba. findGroup gfedcba is not a different order of keywords its a different keyword entirely. This is not a bug as findGroup gfedcba should not return a group named abcdefg.
